#
#
#
variables: 
  test_tag: '2023.01.01.009.ra'

stages:          # List of stages for jobs, and their order of execution
  - preBuild1
  - preBuild2
  - build
  - deploy

show_variables: 
  stage: preBuild1
  tags:
    - gitlab-shared-runner
  script: 
    - echo $CI_COMMIT_REF_NAME

testProd: 
  stage: preBuild2
  tags: 
    - gitlab-shared-runner
  only: 
    refs: 
      - develop
    variables: 
      - $CI_COMMIT_REF_NAME =~ /ra/
  script: 
    - echo ' i am testProd'  


build-gs-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - gitlab-shared-runner
  only:
    refs:
      - develop
    variables:
      - $test == null
  script:
    - docker build -f Dockerfile --build-arg env=dev --build-arg scope=app_gs -t asia-east2-docker.pkg.dev/wgp-project-337610/wgp-video/${CI_PROJECT_NAME}:dev .
    - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin asia-east2-docker.pkg.dev
    - docker push asia-east2-docker.pkg.dev/wgp-project-337610/wgp-video/${CI_PROJECT_NAME}:dev
    - echo "Compile complete."

build-tt-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - gitlab-shared-runner
  only:
    refs:
      - develop
  allow_failure: true
  script:
    - docker build -f Dockerfile --build-arg env=dev --build-arg scope=app_tt -t asia-east2-docker.pkg.dev/wgp-project-337610/wgp-video/${CI_PROJECT_NAME}-tt:dev .
    - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin asia-east2-docker.pkg.dev
    - docker push asia-east2-docker.pkg.dev/wgp-project-337610/wgp-video/${CI_PROJECT_NAME}-tt:dev
    - echo "Compile complete."

build-51ss-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - gitlab-shared-runner
  only:
    refs:
      - develop
  allow_failure: true
  script:
    - docker build -f Dockerfile --build-arg env=dev --build-arg scope=app_51ss -t asia-east2-docker.pkg.dev/wgp-project-337610/wgp-video/${CI_PROJECT_NAME}-51ss:dev .
    - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin asia-east2-docker.pkg.dev
    - docker push asia-east2-docker.pkg.dev/wgp-project-337610/wgp-video/${CI_PROJECT_NAME}-51ss:dev
    - echo "Compile complete."

deploy-gs-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - gitlab-shared-runner
  only:
    refs:
      - develop
  script:
    - echo "Deploying application..."
    - helm upgrade --kubeconfig /home/gitlab-runner/.kube/config-list/dev --install "${CI_PROJECT_NAME}" -f /home/gitlab-runner/hm-helm/helm-charts/stt/${CI_PROJECT_NAME}/values.yaml.dev --set global.release=$(echo "dev-`date +%F-%T`") /home/gitlab-runner/hm-helm/helm-charts/stt/${CI_PROJECT_NAME} -n video-dev
    - echo "Application successfully deployed."
  
deploy-tt-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - gitlab-shared-runner
  only:
    refs:
      - develop
  script:
    - echo "Deploying application..."
    - helm upgrade --kubeconfig /home/gitlab-runner/.kube/config-list/dev --install "${CI_PROJECT_NAME}-tt" -f /home/gitlab-runner/hm-helm/helm-charts/stt/${CI_PROJECT_NAME}-tt/values.yaml.dev --set global.release=$(echo "dev-`date +%F-%T`") /home/gitlab-runner/hm-helm/helm-charts/stt/${CI_PROJECT_NAME}-tt -n video-dev
    - echo "Application successfully deployed."

deploy-51ss-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - gitlab-shared-runner
  only:
    refs:
      - develop
  script:
    - echo "Deploying application..."
    - helm upgrade --kubeconfig /home/gitlab-runner/.kube/config-list/dev --install "${CI_PROJECT_NAME}-51ss" -f /home/gitlab-runner/hm-helm/helm-charts/stt/${CI_PROJECT_NAME}-51ss/values.yaml.dev --set global.release=$(echo "dev-`date +%F-%T`") /home/gitlab-runner/hm-helm/helm-charts/stt/${CI_PROJECT_NAME}-51ss -n video-dev
    - echo "Application successfully deployed."

build-prod-job: 
  stage: build
  tags: 
    - gitlab-shared-runner
  only: 
    refs: 
      - tags
  script: 
    - docker build -f Dockerfile --build-arg env=prod --build-arg scope=app_gs -t asia-east2-docker.pkg.dev/wgp-project-337610/wgp-video/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} .
    - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin asia-east2-docker.pkg.dev
    - docker push asia-east2-docker.pkg.dev/wgp-project-337610/wgp-video/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}

deploy-prod-job: 
  stage: deploy
  tags: 
    - gitlab-shared-runner
  only: 
    refs: 
      - tags
  script: 
    - helm upgrade --kubeconfig /home/gitlab-runner/.kube/config-list/gs --install ${CI_PROJECT_NAME} --wait --set global.release=${CI_COMMIT_TAG} --set global.image.tag=${CI_COMMIT_TAG} /home/gitlab-runner/hm-helm/helm-charts/stt/${CI_PROJECT_NAME} -n prod
    - /bin/bash /home/gitlab-runner/tg-notify.sh gs prod ${CI_PROJECT_NAME} ${CI_COMMIT_TAG}
