name: hm_video_app_workspace

environment:
  sdk: '>=2.19.2 <3.0.0'
  
dev_dependencies:
  melos: ^2.9.0
dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.8.3
  path_provider: ^2.0.12
  
