const Map<String, String> enUsStrings = {
  "game_lobby": "Game Lobby",
  "register_login": "Register Login",
  "close": "Close",
  "open": "Open",
  "cancel": "Cancel",
  "confirm": "Confirm",
  "hot_events": "Hot Events",
  "bank_transfer": "Bank Transfer",
  "trc_address": "TRC-20 Address",
  "account_information": "Account Information",
  "confirmation_of_transfer_and_delivery":
      "Confirmation of transfer and delivery!",
  "transfer_remarks": "Transfer Remarks",
  "please_enter_the_last_digits_of_the_transfer_hash":
      "Please enter the last 5 digits of the transfer hash.",
  "please_enter_your_real_name": "Please enter your real name",
  "account_name": "Account Name",
  "bank_card_number": "Bank Card Number",
  "branch_name": "Branch Name",
  "bank_name": "Bank Name",
  "estimated_amount": "Estimated Amount",
  "exchange_rate": "Exchange Rate",
  "transfer_amount": "Transfer Amount",
  "there_are_no_available_payment_channels_please_try_again_later_or_contact_customer_service":
      "There are no available payment channels, please try again later or contact customer service.",
  "deposit_amount": "Deposit Amount",
  "get_the_link_to_reload": "Get the link to reload...",
  "the_link_was_successful": "The link was successful!",
  "failed_to_get_the_link_to_recharge_please_change_the_recharge_channel_or_contact_customer_service":
      "Failed to get the link to recharge \n Please change the recharge channel or contact customer service.",
  "open_top_up_page": "Open top up page",
  "wrong_name_format": "Wrong name format",
  "wrong_verification_code": "Wrong verification code",
  "if_the_order_is_correct_please_enter_the_above_verification_code":
      "If the order is correct, please enter the above verification code.",
  "deposit": "Deposit",
  "deposit_history": "Deposit History",
  "you_have_been_logged_out_please_log_in_again":
      "You have been logged out, please log in again",
  "warm_tips": "Warm Tips",
  "please_be_sure_to_provide_true_information_to_facilitate_the_verification_of_the_transfer_data":
      "1. Please be sure to provide true information to facilitate the verification of the transfer data.",
  "please_write_the_required_information_in_the_remittance_remarks_to_speed_up_the_recharge_process":
      "2. Please write the required information in the Remittance Remarks to speed up the recharge process.",
  "no_payment_channel": "No Payment Channel",
  "dollar": "Dollar",
  "send_offer": "Send Offer",
  "payment_channel": "Payment Channel",
  "order_confirmation": "Order Confirmation",
  "transaction_failed": "Transaction Failed",
  "there_are_many_people_paying_at_the_moment_please_try_again_later":
      "There are many people paying at the moment, please try again later!",
  "order_creation_failed_please_contact_our_customer_service":
      "Order creation failed, please contact our customer service.",
  "payment_was_not_successful_please_try_to_pay_several_times":
      "1：Payment was not successful, please try to pay several times.",
  "can_not_pull_up_the_payment_order_is_due_to_pull_up_the_order_more_people_please_try_to_pull_up_the_payment_several_times":
      "2：Can not pull up the payment order, is due to pull up the order more people, please try to pull up the payment several times.",
  "please_contact_our_online_customer_service_if_the_recharge_is_successful_but_not_arrived":
      "3：Please contact our online customer service if the recharge is successful but not arrived.",
  "please_select_deposit_amount": "Please select deposit amount",
  "get_recharge_url": "Get recharge URL",
  "we_are_trying_to_get_the_recharge_url_please_wait":
      "We are trying to get the recharge URL, please wait...",
  "please_click_to_open_the_recharge_page":
      "Please click to open the recharge page.",
  "failed_to_get_the_website_address_please_choose_a_new_channel_or_contact_customer_service":
      "Failed to get the website address \n please choose a new channel or contact customer service",
  "please_select_payment_method": "Please select payment method",
  "amount_to_be_paid": "Amount to be paid",
  "confirm_payment": "Confirm payment",
  "completed": "Completed",
  "failed": "Failed",
  "no_record": "No record",
  "confirming": "Confirming",
  "amount": "Amount",
  "order_time": "Order Time",
  "order_number": "Order Number",
  "last_30_days": "Last 30 days",
  "last_7_days": "Last 7 days",
  "yesterday": "Yesterday",
  "today": "Today",
  "application_time_enquiry": "Application Time",
  "status": "Status",
  "payment_confirmation": "Payment Confirmation",
  "bank_card_setting": "Bank Card Setting",
  "please_make_sure_you_fill_in_the_correct_information_to_avoid_affecting_the_payment":
      "Please make sure you fill in the correct information to avoid affecting the payment.",
  "please_enter_your_bank_name": "Please enter your bank name",
  "please_enter_the_name_of_the_branch_optional":
      "Please enter the name of the branch (optional)",
  "card_number": "Card Number",
  "please_enter_your_bank_card_number": "Please enter your bank card number",
  "real_name": "Real Name",
  "account_length": "Account Length 16~19",
  "setup_successful": "Setup Successful",
  "password_length_should_be_digits": "Password length should be 6 digits",
  "input_funds_pin": "Input Funds PIN",
  "please_enter_digits": "Please enter 6 digits",
  "the_password_should_be_the_same_for_the_second_time":
      "The password should be the same for the second time",
  "confirm_password_again": "Confirm password again",
  "please_confirm_the_password_again": "Please confirm the password again",
  "setting_failed": "Setting failed",
  "successful": "Successful",
  "return_to_the_lobby": "Lobby",
  "customer_service": "Customer Service",
  "recharge": "Recharge",
  "quit_the_game": "Quit the game",
  "do_you_really_want_to_quit_the_game": "Do you really want to quit the game",
  "failed_to_withdraw": "Failed to withdraw",
  "withdrawal_history": "Withdrawal History",
  "withdrawal_account": "Withdrawal Account",
  "withdrawal_amount": "Withdrawal amount",
  "application_time": "Application Time",
  "update_time": "Update Time",
  "reviewing": "Reviewing",
  "bank_card": "Bank Card",
  "type": "Type",
  "account": "Account",
  "withdrawal_method": "Withdrawal Method",
  "please_complete_the_card_binding_before_withdrawing_money":
      "Please complete the card binding before withdrawing money",
  'go_to_binding': 'Go to Binding',
  "insufficient_liquidity_please_continue_to_play":
      "Insufficient liquidity, please continue to play",
  "if_you_have_not_reached_the_limit_need_to_pay_the_withdrawal_fee_of_estimated_click_to_confirm_to_send_out_the_withdrawal_order":
      "If you have not reached the stake limit \n need to pay the withdrawal fee of {fee} (estimated)\n Click to confirm to send out the withdrawal order.",
  "please_set_the_password_first": "Please set the password first",
  'go_to_settings': 'Go to Settings',
  "game_withdrawal": "Game Withdrawal",
  "limit": "Stake Limit",
  "achieved": "Achieved",
  "not_reached": "Not reached",
  "please_enter_the_withdrawal_amount": "Please enter the withdrawal amount",
  "input_amount_must_not_be_less_than": "Input amount must not be less than",
  "input_amount_must_not_be_greater_than_the_remaining_balance":
      "Input amount must not be greater than the remaining balance",
  "input_amount_is_in_wrong_format": "Input amount is in wrong format",
  "minimum_withdrawal_amount_is": "Minimum withdrawal amount is",
  "application_completed": "Application Completed",
  "withdrawal_application_has_been_completed_you_can_check_the_current_application_status_in_the_withdrawal_log":
      "Withdrawal application has been completed, you can check the current application status in the withdrawal log.",
  "minimum_withdrawable_amount": "Minimum Withdrawable Amount",
  "flow_limit_details": "Stake Limit Details",
  "accumulated_liquidity": "Accumulated Liquidity",
  "withdrawal_fee_will_be_charged_for_withdrawal_before_reaching_the_limit":
      "Withdrawal fee will be charged for withdrawal before reaching the limit.",
  "login_now": "Login Now",
  "no_account_yet": "No account yet",
  "forgot_your_password": "Forgot your password?",
  "please_enter_your_password": "Please enter your password",
  "password": "Password",
  "username": "Username",
  "letters_and_numbers": "6~12 letters and numbers",
  "password_is_letters_and_numbers": "Password is 8-20 letters and numbers",
  "account_is_digits_alphabetic_and_numeric":
      "Account is 6~12 digits alphabetic and numeric",
  "please_enter_your_username": "Please enter your username",
  "incorrect_username_or_password": "Incorrect username or password",
  "login_error": "Login Error",
  "login_successful": "Login Successful",
  "register_now": "Register Now",
  "verify_password": "Verify Password",
  "incorrect_secondary_password": "Incorrect secondary password",
  "registration_error": "Registration Error",
  "registration_successful": "Registration Successful",
  "download_app": "Download APP",
  "greetings_to_our_valued_users_global_gaming_invites_you_to_download_the_app_to_enhance_your_gaming_experience":
      "Greetings to our valued users \n Global Gaming invites you to download the APP to enhance your gaming experience.",
  "this_password_is_only_for_the_first_time_you_log_in_to_the_app_please_be_sure_to_change_your_password_after_logging_in":
      "This password is only for the first time you log in to the APP \nPlease be sure to change your password after logging in.",
  "password_copied": "Password copied",
  "account_has_been_copied": "Account has been copied",
  "withdrawal": "Withdrawal",
  "balance": "Balance",
  "insufficient_password": "Insufficient password",
  "wrong_password": "Wrong password",
  "duplicate_login": "Duplicate Login",
  "duplicated": "Duplicated",
  "currently_under_maintenance": "Currently under maintenance",
  "estimated_maintenance_time": "Estimated maintenance time 08:00-10:00",
  "please_try_again_later_sorry_for_the_inconvenience":
      "Please try again later, sorry for the inconvenience.",
  "game_maintenance_in_progress": "game_maintenance_in_progress",
  "the_game_is_under_maintenance_please_try_again_later":
      "The game is under maintenance, please try again later.",
  "login": "login",
  "register": "register",
  "please_contact_customer_service_or_log_in_with_your_id_card":
      "Please contact customer service or log in with your ID card.",
  "all": "All",
  "recent": "Recent",
  "fish": "Fish",
  "card": "Card",
  "slots": "Slots",
  "live": "Live",
  "sports": "Sports",
  "lottery": "Lottery",
  "alipay": "Alipay",
  "wechat": "Wechat",
  "bank": "Bank",
  "set_a_funds_pin": "Set a Funds PIN",
  "funds_pin": "Funds PIN",
  "tips": "Tips",
};
