const Map<String, String> idIdStrings = {
  "game_lobby": "Lobi Permainan",
  "register_login": "Daftar/Masuk",
  "close": "Tutup",
  "open": "Buka",
  "cancel": "Batal",
  "confirm": "Konfirmasi",
  "hot_events": "Acara Terpopuler",
  "bank_transfer": "Transfer Bank",
  "trc_address": "Alamat TRC-20",
  "account_information": "Informasi Akun",
  "confirmation_of_transfer_and_delivery":
      "Konfirmasi Transfer dan Pengiriman!",
  "transfer_remarks": "Catatan Transfer",
  "please_enter_the_last_digits_of_the_transfer_hash":
      "Silakan masukkan 5 digit terakhir dari hash transfer.",
  "please_enter_your_real_name": "Silakan masukkan nama asli Anda",
  "account_name": "Nama Akun",
  "bank_card_number": "Nomor Kartu Bank",
  "branch_name": "Nama Cabang",
  "bank_name": "Nama Bank",
  "estimated_amount": "Jumlah yang Diestimasikan",
  "exchange_rate": "Kurs",
  "transfer_amount": "Jumlah Transfer",
  "there_are_no_available_payment_channels_please_try_again_later_or_contact_customer_service":
      "Tidak ada saluran pembayaran yang tersedia, coba lagi nanti atau hubungi layanan pelanggan.",
  "deposit_amount": "Jumlah Deposit",
  "get_the_link_to_reload": "Mendapatkan tautan untuk isi ulang...",
  "the_link_was_successful": "Tautan berhasil!",
  "failed_to_get_the_link_to_recharge_please_change_the_recharge_channel_or_contact_customer_service":
      "Gagal mendapatkan tautan untuk mengisi ulang. Silakan ubah saluran pengisian ulang atau hubungi layanan pelanggan.",
  "open_top_up_page": "Buka halaman isi ulang",
  "wrong_name_format": "Format nama salah",
  "wrong_verification_code": "Kode verifikasi salah",
  "if_the_order_is_correct_please_enter_the_above_verification_code":
      "Jika pesanan benar, silakan masukkan kode verifikasi di atas.",
  "deposit": "Setoran",
  "deposit_history": "Riwayat Deposit",
  "you_have_been_logged_out_please_log_in_again":
      "Anda telah keluar, silakan login kembali",
  "warm_tips": "Tips Hangat",
  "please_be_sure_to_provide_true_information_to_facilitate_the_verification_of_the_transfer_data":
      "Harap pastikan untuk memberikan informasi yang benar untuk memfasilitasi verifikasi data transfer.",
  "please_write_the_required_information_in_the_remittance_remarks_to_speed_up_the_recharge_process":
      "Harap tulis informasi yang diperlukan dalam Catatan Remitansi untuk mempercepat proses isi ulang.",
  "no_payment_channel": "Tidak ada Saluran Pembayaran",
  "dollar": "Dolar",
  "send_offer": "Kirim Penawaran",
  "payment_channel": "Saluran Pembayaran",
  "order_confirmation": "Konfirmasi Pesanan",
  "transaction_failed": "Transaksi Gagal",
  "there_are_many_people_paying_at_the_moment_please_try_again_later":
      "Saat ini banyak orang yang membayar, silakan coba lagi nanti!",
  "order_creation_failed_please_contact_our_customer_service":
      "Pembuatan pesanan gagal, silakan hubungi layanan pelanggan kami.",
  "payment_was_not_successful_please_try_to_pay_several_times":
      "Pembayaran tidak berhasil, silakan coba membayar beberapa kali.",
  "can_not_pull_up_the_payment_order_is_due_to_pull_up_the_order_more_people_please_try_to_pull_up_the_payment_several_times":
      "Tidak bisa membuka pesanan pembayaran karena lebih banyak orang membuka pesanan, silakan coba membuka pesanan pembayaran beberapa kali.",
  "please_contact_our_online_customer_service_if_the_recharge_is_successful_but_not_arrived":
      "Silakan hubungi layanan pelanggan online kami jika pengisian ulang berhasil tetapi belum tiba.",
  "please_select_deposit_amount": "Silakan pilih jumlah deposit",
  "get_recharge_url": "Dapatkan URL pengisian ulang",
  "we_are_trying_to_get_the_recharge_url_please_wait":
      "Kami sedang mencoba mendapatkan URL pengisian ulang, silakan tunggu...",
  "please_click_to_open_the_recharge_page":
      "Silakan klik untuk membuka halaman pengisian ulang.",
  "failed_to_get_the_website_address_please_choose_a_new_channel_or_contact_customer_service":
      "Gagal mendapatkan alamat situs web. Silakan pilih saluran baru atau hubungi layanan pelanggan.",
  "please_select_payment_method": "Silakan pilih metode pembayaran",
  "amount_to_be_paid": "Jumlah yang Harus Dibayar",
  "confirm_payment": "Konfirmasi Pembayaran",
  "completed": "Selesai",
  "failed": "Gagal",
  "no_record": "Tidak ada Catatan",
  "confirming": "Sedang Dikonfirmasi",
  "amount": "Jumlah",
  "order_time": "Waktu Pesanan",
  "order_number": "Nomor Pesanan",
  "last_30_days": "30 hari terakhir",
  "last_7_days": "7 hari terakhir",
  "yesterday": "Kemarin",
  "today": "Hari Ini",
  "application_time_enquiry": "Waktu Pengajuan",
  "status": "Status",
  "payment_confirmation": "Konfirmasi Pembayaran",
  "bank_card_setting": "Pengaturan Kartu Bank",
  "please_make_sure_you_fill_in_the_correct_information_to_avoid_affecting_the_payment":
      "Pastikan Anda mengisi informasi yang benar untuk menghindari pengaruh pada pembayaran.",
  "please_enter_your_bank_name": "Silakan masukkan nama bank Anda",
  "please_enter_the_name_of_the_branch_optional":
      "Silakan masukkan nama cabang (opsional)",
  "card_number": "Nomor Kartu",
  "please_enter_your_bank_card_number":
      "Silakan masukkan nomor kartu bank Anda",
  "real_name": "Nama Asli",
  "account_length": "Panjang Akun 16~19",
  "setup_successful": "Pengaturan Berhasil",
  "password_length_should_be_digits": "Panjang kata sandi harus 6 digit",
  "input_funds_pin": "Masukkan PIN Dana",
  "please_enter_digits": "Silakan masukkan 6 digit",
  "the_password_should_be_the_same_for_the_second_time":
      "Kata sandi harus sama untuk kedua kalinya",
  "confirm_password_again": "Konfirmasi kata sandi lagi",
  "please_confirm_the_password_again": "Silakan konfirmasi kata sandi lagi",
  "setting_failed": "Pengaturan gagal",
  "successful": "Berhasil",
  "return_to_the_lobby": "Kembali ke lobi",
  "customer_service": "Layanan Pelanggan",
  "recharge": "Isi Ulang",
  "quit_the_game": "Keluar dari permainan",
  "do_you_really_want_to_quit_the_game":
      "Apakah Anda benar-benar ingin keluar dari permainan?",
  "failed_to_withdraw": "Gagal melakukan penarikan",
  "withdrawal_history": "Riwayat Penarikan",
  "withdrawal_account": "Akun Penarikan",
  "withdrawal_amount": "Jumlah Penarikan",
  "application_time": "Waktu Pengajuan",
  "update_time": "Waktu Pembaruan",
  "reviewing": "Sedang Ditinjau",
  "bank_card": "Kartu Bank",
  "type": "Tipe",
  "account": "Akun",
  "withdrawal_method": "Metode Penarikan",
  "please_complete_the_card_binding_before_withdrawing_money":
      "Silakan selesaikan pengikatan kartu sebelum menarik uang.",
  "go_to_binding": "Pergi untuk Pengikatan",
  "insufficient_liquidity_please_continue_to_play":
      "Likuiditas tidak cukup, silakan terus bermain",
  "if_you_have_not_reached_the_limit_need_to_pay_the_withdrawal_fee_of_estimated_click_to_confirm_to_send_out_the_withdrawal_order":
      "Jika Anda belum mencapai batas taruhan \n perlu membayar biaya penarikan sebesar {fee} (perkiraan)\n Klik untuk konfirmasi mengirimkan pesanan penarikan.",
  "please_set_the_password_first": "Silakan atur kata sandi terlebih dahulu",
  "go_to_settings": "Pergi ke Pengaturan",
  "game_withdrawal": "Penarikan Permainan",
  "limit": "Batas Taruhan",
  "achieved": "Tercapai",
  "not_reached": "Belum tercapai",
  "please_enter_the_withdrawal_amount": "Silakan masukkan jumlah penarikan",
  "input_amount_must_not_be_less_than":
      "Jumlah yang dimasukkan tidak boleh kurang dari {amount}",
  "input_amount_must_not_be_greater_than_the_remaining_balance":
      "Jumlah masukan tidak boleh lebih dari saldo yang tersisa",
  "input_amount_is_in_wrong_format": "Format jumlah masukan salah",
  "minimum_withdrawal_amount_is": "Minimal penarikan: {amount} IDR",
  "application_completed": "Aplikasi Selesai",
  "withdrawal_application_has_been_completed_you_can_check_the_current_application_status_in_the_withdrawal_log":
      "Pengajuan penarikan telah selesai, Anda dapat memeriksa status pengajuan saat ini di log penarikan.",
  "minimum_withdrawable_amount": "Jumlah Penarikan Minimum",
  "flow_limit_details": "Detail Batas Taruhan",
  "accumulated_liquidity": "Likuiditas Terakumulasi",
  "withdrawal_fee_will_be_charged_for_withdrawal_before_reaching_the_limit":
      "Biaya penarikan {fee} % akan dikenakan untuk penarikan sebelum mencapai batas.",
  "login_now": "Masuk Sekarang",
  "no_account_yet": "Belum punya akun",
  "forgot_your_password": "Lupa kata sandi?",
  "please_enter_your_password": "Silakan masukkan kata sandi Anda",
  "password": "Kata Sandi",
  "username": "Nama Pengguna",
  "letters_and_numbers": "6~12 huruf dan angka",
  "password_is_letters_and_numbers": "Kata sandi adalah 8-20 huruf dan angka",
  "account_is_digits_alphabetic_and_numeric":
      "Akun adalah 6~12 digit alfabet dan numerik",
  "please_enter_your_username": "Silakan masukkan username Anda",
  "incorrect_username_or_password": "Username atau kata sandi salah",
  "login_error": "Kesalahan Login",
  "login_successful": "Login Berhasil",
  "register_now": "Daftar Sekarang",
  "verify_password": "Verifikasi Kata Sandi",
  "incorrect_secondary_password": "Kata sandi sekunder salah",
  "registration_error": "Kesalahan Pendaftaran",
  "registration_successful": "Pendaftaran Berhasil",
  "download_app": "Unduh APP",
  "greetings_to_our_valued_users_global_gaming_invites_you_to_download_the_app_to_enhance_your_gaming_experience":
      "Salam untuk pengguna kami yang terhormat, \n Global Gaming mengundang Anda untuk mengunduh APLIKASI agar pengalaman bermain game Anda semakin meningkat.",
  "this_password_is_only_for_the_first_time_you_log_in_to_the_app_please_be_sure_to_change_your_password_after_logging_in":
      "Kata sandi ini hanya untuk pertama kali Anda masuk ke APP \nPastikan untuk mengubah kata sandi Anda setelah masuk.",
  "password_copied": "Kata sandi disalin",
  "account_has_been_copied": "Akun telah disalin",
  "withdrawal": "Penarikan",
  "balance": "Saldo",
  "insufficient_password": "Kata sandi tidak cukup",
  "wrong_password": "Kata sandi salah",
  "duplicate_login": "Login ganda",
  "duplicated": "Terduplikasi",
  "currently_under_maintenance": "Sedang dalam perawatan",
  "estimated_maintenance_time": "Perkiraan waktu perawatan 08:00-10:00",
  "please_try_again_later_sorry_for_the_inconvenience":
      "Silakan coba lagi nanti, maaf atas ketidaknyamanannya.",
  "game_maintenance_in_progress": "perawatan game sedang berlangsung",
  "the_game_is_under_maintenance_please_try_again_later":
      "Game sedang dalam pemeliharaan, silakan coba lagi nanti",
  "login": "Masuk",
  "register": "Daftar",
  "please_contact_customer_service_or_log_in_with_your_id_card":
      "Silakan hubungi layanan pelanggan atau masuk dengan kartu identitas Anda",
  "all": "Semua",
  "recent": "Terbaru",
  "fish": "Ikan",
  "card": "Kartu",
  "slots": "Slot",
  "live": "Langsung",
  "sports": "Olahraga",
  "lottery": "Undian",
  "alipay": "Alipay",
  "wechat": "WeChat",
  "bank": "Bank",
  "set_a_funds_pin": "Atur PIN Dana",
  "funds_pin": "PIN Dana",
  "tips": "Tips"
};
