const Map<String, String> viVnStrings = {
  "game_lobby": "Sảnh Game",
  "register_login": "Đăng ký/Đăng nhập",
  "close": "Đóng",
  "open": "Mở",
  "cancel": "Hủy",
  "confirm": "Xác nhận",
  "hot_events": "Sự kiện nóng",
  "bank_transfer": "Chuyển khoản ngân hàng",
  "trc_address": "Địa chỉ TRC-20",
  "account_information": "Thông tin tài khoản",
  "confirmation_of_transfer_and_delivery":
      "Xác nhận chuyển khoản và giao hàng!",
  "transfer_remarks": "Ghi chú chuyển khoản",
  "please_enter_the_last_digits_of_the_transfer_hash":
      "Vui lòng nhập 5 chữ số cuối cùng của mã băm chuyển khoản.",
  "please_enter_your_real_name":
      "Vui lòng nhập 5 chữ số cuối của mã hash chuyển khoản.",
  "account_name": "Tên tài khoản",
  "bank_card_number": "Số thẻ ngân hàng",
  "branch_name": "Tên chi nhánh",
  "bank_name": "Tên ngân hàng",
  "estimated_amount": "Số tiền Ước lượng",
  "exchange_rate": "Tỷ giá",
  "transfer_amount": "Số tiền chuyển khoản",
  "there_are_no_available_payment_channels_please_try_again_later_or_contact_customer_service":
      "Không có kênh thanh toán nào khả dụng, vui lòng thử lại sau hoặc liên hệ với dịch vụ khách hàng.",
  "deposit_amount": "Số tiền Gửi",
  "get_the_link_to_reload": "Lấy đường link để nạp tiền...",
  "the_link_was_successful": "Đường link đã thành công!",
  "failed_to_get_the_link_to_recharge_please_change_the_recharge_channel_or_contact_customer_service":
      "Không lấy được đường link để nạp tiền. Vui lòng thay đổi kênh nạp tiền hoặc liên hệ với dịch vụ khách hàng.",
  "open_top_up_page": "Mở trang nạp tiền",
  "wrong_name_format": "Định dạng tên sai",
  "wrong_verification_code": "Mã xác minh sai",
  "if_the_order_is_correct_please_enter_the_above_verification_code":
      "Nếu đơn hàng đúng, vui lòng nhập mã xác minh ở trên.",
  "deposit": "Gửi tiền",
  "deposit_history": "Lịch sử Gửi tiền",
  "you_have_been_logged_out_please_log_in_again":
      "Bạn đã bị đăng xuất, vui lòng đăng nhập lại",
  "warm_tips": "Lời khuyên ấm áp",
  "please_be_sure_to_provide_true_information_to_facilitate_the_verification_of_the_transfer_data":
      "1. Vui lòng chắc chắn cung cấp thông tin chính xác để thuận tiện cho việc xác minh dữ liệu chuyển khoản.",
  "please_write_the_required_information_in_the_remittance_remarks_to_speed_up_the_recharge_process":
      "2. Vui lòng viết thông tin yêu cầu vào Ghi chú Chuyển khoản để tăng tốc độ nạp tiền.",
  "no_payment_channel": "Không có Kênh Thanh toán",
  "dollar": "Đô la",
  "send_offer": "Gửi Ưu đãi",
  "payment_channel": "Kênh thanh toán",
  "order_confirmation": "Xác nhận đơn hàng",
  "transaction_failed": "Giao dịch Thất bại",
  "there_are_many_people_paying_at_the_moment_please_try_again_later":
      "Hiện có nhiều người thanh toán, vui lòng thử lại sau!",
  "order_creation_failed_please_contact_our_customer_service":
      "Tạo đơn hàng thất bại, vui lòng liên hệ với dịch vụ khách hàng của chúng tôi.",
  "payment_was_not_successful_please_try_to_pay_several_times":
      "1: Thanh toán không thành công, vui lòng thử thanh toán nhiều lần.",
  "can_not_pull_up_the_payment_order_is_due_to_pull_up_the_order_more_people_please_try_to_pull_up_the_payment_several_times":
      "2: Không thể kéo đơn hàng thanh toán, do có nhiều người kéo đơn hàng, vui lòng thử kéo đơn hàng thanh toán nhiều lần.",
  "please_contact_our_online_customer_service_if_the_recharge_is_successful_but_not_arrived":
      "3: Vui lòng liên hệ với dịch vụ khách hàng trực tuyến của chúng tôi nếu nạp tiền thành công nhưng không đến.",
  "please_select_deposit_amount": "Vui lòng chọn số tiền gửi",
  "get_recharge_url": "Lấy URL nạp tiền",
  "we_are_trying_to_get_the_recharge_url_please_wait":
      "Chúng tôi đang cố gắng lấy URL nạp tiền, vui lòng chờ...",
  "please_click_to_open_the_recharge_page":
      "Vui lòng nhấp để mở trang nạp tiền.",
  "failed_to_get_the_website_address_please_choose_a_new_channel_or_contact_customer_service":
      "Không lấy được địa chỉ trang web, vui lòng chọn kênh mới hoặc liên hệ với dịch vụ khách hàng",
  "please_select_payment_method": "Vui lòng chọn phương thức thanh toán",
  "amount_to_be_paid": "Số tiền cần thanh toán",
  "confirm_payment": "Xác nhận thanh toán",
  "completed": "Hoàn thành",
  "failed": "Thất bại",
  "no_record": "Không có bản ghi",
  "confirming": "Đang xác nhận",
  "amount": "Số tiền",
  "order_time": "Thời gian đặt hàng",
  "order_number": "Số đơn hàng",
  "last_30_days": "30 ngày gần đây",
  "last_7_days": "7 ngày gần đây",
  "yesterday": "Hôm qua",
  "today": "Hôm nay",
  "application_time_enquiry": "Thời gian Ứng dụng",
  "status": "Trạng thái",
  "payment_confirmation": "Xác nhận Thanh toán",
  "bank_card_setting": "Cài đặt Thẻ ngân hàng",
  "please_make_sure_you_fill_in_the_correct_information_to_avoid_affecting_the_payment":
      "Vui lòng chắc chắn bạn điền đúng thông tin để tránh ảnh hưởng đến việc thanh toán.",
  "please_enter_your_bank_name": "Vui lòng nhập tên ngân hàng của bạn",
  "please_enter_the_name_of_the_branch_optional":
      "Vui lòng nhập tên chi nhánh (tùy chọn)",
  "card_number": "Số thẻ",
  "please_enter_your_bank_card_number":
      "Vui lòng nhập số thẻ ngân hàng của bạn",
  "real_name": "Tên thật",
  "account_length": "Độ dài Tài khoản 16~19",
  "setup_successful": "Thiết lập Thành công",
  "password_length_should_be_digits": "Độ dài mật khẩu phải là 6 chữ số",
  "input_funds_pin": "Nhập Mã PIN Quỹ",
  "please_enter_digits": "Vui lòng nhập 6 chữ số",
  "the_password_should_be_the_same_for_the_second_time":
      "Mật khẩu phải giống nhau khi nhập lần thứ hai",
  "confirm_password_again": "Xác nhận lại mật khẩu",
  "please_confirm_the_password_again": "Vui lòng xác nhận lại mật khẩu",
  "setting_failed": "Thiết lập Thất bại",
  "successful": "Thành công",
  "return_to_the_lobby": "Quay lại sảnh",
  "customer_service": "Nạp tiền",
  "recharge": "Nạp tiền",
  "quit_the_game": "Thoát trò chơi",
  "do_you_really_want_to_quit_the_game":
      "Bạn có thực sự muốn thoát trò chơi không?",
  "failed_to_withdraw": "Không thể rút tiền",
  "withdrawal_history": "Lịch sử Rút tiền",
  "withdrawal_account": "Tài khoản Rút tiền",
  "withdrawal_amount": "Số tiền Rút",
  "application_time": "Thời gian Ứng dụng",
  "update_time": "Thời gian Cập nhật",
  "reviewing": "Đang xem xét",
  "bank_card": "Thẻ Ngân hàng",
  "type": "Loại",
  "account": "Tài khoản",
  "withdrawal_method": "Phương thức Rút tiền",
  "please_complete_the_card_binding_before_withdrawing_money":
      "Vui lòng hoàn thành việc liên kết thẻ trước khi rút tiền.",
  "go_to_binding": "Đi đến Liên kết",
  "insufficient_liquidity_please_continue_to_play":
      "Likuiditas tidak cukup, silakan lanjutkan bermain",
  "if_you_have_not_reached_the_limit_need_to_pay_the_withdrawal_fee_of_estimated_click_to_confirm_to_send_out_the_withdrawal_order":
      "Jika Anda belum mencapai batas taruhan \n perlu membayar biaya penarikan sebesar {fee} (perkiraan)\n Klik untuk mengonfirmasi untuk mengirimkan pesanan penarikan.",
  "please_set_the_password_first": "Vui lòng thiết lập mật khẩu trước",
  "go_to_settings": "Đi đến Cài đặt",
  "game_withdrawal": "Rút tiền từ Trò chơi",
  "limit": "Giới hạn Cược",
  "achieved": "Đã đạt",
  "not_reached": "Chưa đạt",
  "please_enter_the_withdrawal_amount": "Vui lòng nhập số tiền rút",
  "input_amount_must_not_be_less_than":
      "Số tiền nhập vào không được ít hơn {amount}.",
  "input_amount_must_not_be_greater_than_the_remaining_balance":
      "Số tiền nhập vào không được nhiều hơn số dư còn lại",
  "input_amount_is_in_wrong_format": "Định dạng số tiền nhập vào không đúng",
  "minimum_withdrawal_amount_is": "Số tiền rút tối thiểu là {amount}",
  "application_completed": "Ứng dụng đã Hoàn thành",
  "withdrawal_application_has_been_completed_you_can_check_the_current_application_status_in_the_withdrawal_log":
      "Ứng dụng rút tiền đã hoàn thành, bạn có thể kiểm tra trạng thái ứng dụng hiện tại trong nhật ký rút tiền.",
  "minimum_withdrawable_amount": "Số tiền Tối thiểu Có thể Rút",
  "flow_limit_details": "Chi tiết Giới hạn Cược",
  "accumulated_liquidity": "Likuiditas Terakumulasi",
  "withdrawal_fee_will_be_charged_for_withdrawal_before_reaching_the_limit":
      "Phí rút tiền {fee} % sẽ được tính cho lần rút tiền trước khi đạt giới hạn.",
  "login_now": "Đăng nhập Ngay",
  "no_account_yet": "Chưa có tài khoản",
  "forgot_your_password": "Quên mật khẩu của bạn?",
  "please_enter_your_password": "Vui lòng nhập mật khẩu của bạn",
  "password": "Mật khẩu",
  "username": "Tên đăng nhập",
  "letters_and_numbers": "6~12 chữ cái và số",
  "password_is_letters_and_numbers": "Mật khẩu là 8-20 chữ cái và số",
  "account_is_digits_alphabetic_and_numeric":
      "Tài khoản là 6~12 chữ số chữ cái và số",
  "please_enter_your_username": "Vui lòng nhập tên đăng nhập của bạn",
  "incorrect_username_or_password": "Tên đăng nhập hoặc mật khẩu không đúng",
  "login_error": "Lỗi Đăng nhập",
  "login_successful": "Đăng nhập Thành công",
  "register_now": "Đăng ký Ngay",
  "verify_password": "Xác minh Mật khẩu",
  "incorrect_secondary_password": "Mật khẩu phụ không đúng",
  "registration_error": "Lỗi Đăng ký",
  "registration_successful": "Đăng ký Thành công",
  "download_app": "Tải xuống Ứng dụng",
  "greetings_to_our_valued_users_global_gaming_invites_you_to_download_the_app_to_enhance_your_gaming_experience":
      "Chào mừng người dùng quý giá của chúng tôi, Global Gaming mời bạn tải xuống APP để cải thiện trải nghiệm chơi game của mình.",
  "this_password_is_only_for_the_first_time_you_log_in_to_the_app_please_be_sure_to_change_your_password_after_logging_in":
      "Mật khẩu này chỉ dùng cho lần đầu tiên bạn đăng nhập vào APP, vui lòng đảm bảo thay đổi mật khẩu sau khi đăng nhập.",
  "password_copied": "Mật khẩu đã được sao chép",
  "account_has_been_copied": "Tài khoản đã được sao chép",
  "withdrawal": "Rút tiền",
  "balance": "Số dưủ",
  "insufficient_password": "Mật khẩu không đủ",
  "wrong_password": "Mật khẩu sai",
  "duplicate_login": "Đăng nhập trùng lặp",
  "duplicated": "Đã được sao chép",
  "currently_under_maintenance": "Đang bảo trì",
  "estimated_maintenance_time": "Thời gian bảo trì dự kiến 08:00-10:00",
  "please_try_again_later_sorry_for_the_inconvenience":
      "Vui lòng thử lại sau, xin lỗi vì sự bất tiện này.",
  "game_maintenance_in_progress": "bảo trì_trò_chơi_đang_diễn_ra",
  "the_game_is_under_maintenance_please_try_again_later":
      "Trò chơi đang được bảo trì, vui lòng thử lại sau.",
  "login": "đăng nhập",
  "register": "đăng ký",
  "please_contact_customer_service_or_log_in_with_your_id_card":
      "Vui lòng liên hệ với dịch vụ khách hàng hoặc đăng nhập bằng thẻ ID của bạn.",
  "all": "Tất cả",
  "recent": "Gần đây",
  "fish": "Cá",
  "card": "Bài",
  "slots": "Máy đánh bạc",
  "live": "Trực tiếp",
  "sports": "Thể thao",
  "lottery": "Xổ số",
  "hot": "Nổi bật",
  "alipay": "Alipay",
  "wechat": "WeChat",
  "bank": "Ngân hàng",
  "set_a_funds_pin": "Thiết lập mã PIN Quỹ",
  "funds_pin": "Mã PIN Quỹ",
  "tips": "Mẹo",
};
