const Map<String, String> zhTwStrings = {
  'game_lobby': '遊戲大廳',
  'register_login': '註冊/登入',
  'close': '關閉',
  'open': '開啟',
  'cancel': '取消',
  'confirm': '確認',
  'hot_events': '熱門活動',
  'bank_transfer': '銀行轉帳',
  'trc_address': 'TRC-20地址',
  'account_information': '帳戶資訊',
  'confirmation_of_transfer_and_delivery': '確認已轉帳，送出！',
  'transfer_remarks': '轉帳備註',
  'please_enter_the_last_digits_of_the_transfer_hash': '請輸入轉帳哈希值末 5 碼',
  'please_enter_your_real_name': '請輸入真實姓名',
  'account_name': '帳戶姓名',
  'bank_card_number': '銀行卡號',
  'branch_name': '支行名稱',
  'bank_name': '銀行名稱',
  'estimated_amount': '預估上分金額',
  'exchange_rate': '匯率',
  'transfer_amount': '轉帳金額',
  'there_are_no_available_payment_channels_please_try_again_later_or_contact_customer_service':
      '當前無可用支付渠道，請稍候再試或聯繫客服。',
  'deposit_amount': '存款金額',
  'get_the_link_to_reload': '取得充值連結...',
  'the_link_was_successful': '充值連結取得成功！',
  'failed_to_get_the_link_to_recharge_please_change_the_recharge_channel_or_contact_customer_service':
      '充值連結取得失敗\n請更換充值渠道或聯繫客服',
  'open_top_up_page': '開啟充值頁',
  'wrong_name_format': '姓名格式錯誤',
  'wrong_verification_code': '驗證碼錯誤',
  'if_the_order_is_correct_please_enter_the_above_verification_code':
      '如訂單無誤，請輸入以上驗證碼',
  'deposit': '存款',
  'deposit_history': '存款記錄',
  'you_have_been_logged_out_please_log_in_again': '你已被登出，請重新登入',
  'warm_tips': '溫馨提示',
  'please_be_sure_to_provide_true_information_to_facilitate_the_verification_of_the_transfer_data':
      '1. 請務必提供真實資訊，以利核對轉帳資料。',
  'please_write_the_required_information_in_the_remittance_remarks_to_speed_up_the_recharge_process':
      '2. 請在匯款備註寫入要求資訊，加速充值流程。',
  'no_payment_channel': '沒有支付通道',
  'dollar': '',
  'send_offer': '送優惠',
  'payment_channel': '支付渠道',
  'order_confirmation': '訂單確認',
  'transaction_failed': '交易失敗',
  'there_are_many_people_paying_at_the_moment_please_try_again_later':
      '當前支付人數眾多，請稍後再試！',
  'order_creation_failed_please_contact_our_customer_service': '訂單建立失敗，請聯繫客服',
  'payment_was_not_successful_please_try_to_pay_several_times':
      '1：支付不成功，請多次嘗試支付。',
  'can_not_pull_up_the_payment_order_is_due_to_pull_up_the_order_more_people_please_try_to_pull_up_the_payment_several_times':
      '2：無法拉起支付訂單，是由於拉起訂單人數較多，請多次嘗試拉起支付。',
  'please_contact_our_online_customer_service_if_the_recharge_is_successful_but_not_arrived':
      '3：充值成功未到賬，請聯繫在線客服。',
  'please_select_deposit_amount': '請選擇存款金額',
  'get_recharge_url': '取得充值網址',
  'we_are_trying_to_get_the_recharge_url_please_wait': '正在努力取得充值網址，請稍候...',
  'please_click_to_open_the_recharge_page': '已取得充值網址，點擊開啟充值頁',
  'failed_to_get_the_website_address_please_choose_a_new_channel_or_contact_customer_service':
      '取得網址失敗\n請重新選擇渠道或聯繫客服',
  'please_select_payment_method': '請選擇支付方式',
  'amount_to_be_paid': '需支付金額',
  'confirm_payment': '確認支付',
  'completed': '已完成',
  'failed': '失敗',
  'no_record': '暫無紀錄',
  'confirming': '確認中',
  'amount': '金額',
  'order_time': '訂單時間',
  'order_number': '訂單編號',
  'last_30_days': '近三十日',
  'last_7_days': '近七天',
  'yesterday': '昨天',
  'today': '今天',
  'application_time_enquiry': '申請時間查詢',
  'status': '狀態',
  'payment_confirmation': '支付確認',
  'bank_card_setting': '銀行卡設置',
  'please_make_sure_you_fill_in_the_correct_information_to_avoid_affecting_the_payment':
      '綁定後不可更改，請確認資料填寫正確，避免影響到帳。',
  'please_enter_your_bank_name': '請輸入銀行名稱',
  'please_enter_the_correct_bank_name': '請輸入正確的銀行名稱',
  'please_enter_the_name_of_the_branch_optional': '請輸入支行名稱(選填)',
  'card_number': '銀行卡號',
  'please_enter_your_bank_card_number': '請輸入您的銀行卡號',
  'real_name': '真實姓名',
  'account_length': '帳戶長度為16~19',
  'setup_successful': '設置成功',
  'password_length_should_be_digits': '密碼長度應為6位數',
  'input_funds_pin': '輸入資金密碼',
  'please_enter_digits': '請輸入6位數字',
  'the_password_should_be_the_same_for_the_second_time': '二次驗證密碼輸入應相同',
  'confirm_password_again': '再次確認密碼',
  'please_confirm_the_password_again': '請再次確認密碼',
  'setting_failed': '設置失敗',
  'successful': '設置成功',
  'return_to_the_lobby': '返回大廳',
  'customer_service': '客服',
  'recharge': '充值',
  'quit_the_game': '退出遊戲',
  'do_you_really_want_to_quit_the_game': '你真的要退出遊戲嗎？',
  'failed_to_withdraw': '出款失敗',
  'withdrawal_history': '提現紀錄',
  'withdrawal_account': '提款帳戶',
  'withdrawal_amount': '提款金額',
  'application_time': '申請時間',
  'update_time': '更新時間',
  'reviewing': '審核中',
  'bank_card': '銀行卡',
  'bank_card_idr': '銀行卡',
  'bank_card_twd': '銀行卡',
  'bank_card_php': '銀行卡',
  'type': '類型',
  'account': '帳戶',
  'withdrawal_method': '提現方式',
  'please_complete_the_card_binding_before_withdrawing_money':
      '請完成銀行卡綁定，方可進行提款',
  'go_to_binding': '前往綁定',
  'insufficient_liquidity_please_continue_to_play': '流水不足，請繼續遊戲',
  'if_you_have_not_reached_the_limit_need_to_pay_the_withdrawal_fee_of_estimated_click_to_confirm_to_send_out_the_withdrawal_order':
      '未達成流水限額\n需自行負擔提現手續費 {fee} 元(預估)\n點擊確認送出提現訂單',
  'please_set_the_password_first': '請先設置資金密碼',
  'go_to_settings': '前往設定',
  'game_withdrawal': '遊戲提現',
  'limit': '流水限額',
  'achieved': '已達標',
  'not_reached': '未達標',
  'please_enter_the_withdrawal_amount': '請輸入提現金額',
  'input_amount_must_not_be_less_than': '輸入金額不得小於',
  'input_amount_must_not_be_greater_than_the_remaining_balance': '輸入金額不得大於餘額',
  'input_amount_is_in_wrong_format': '輸入金額格式錯誤',
  'minimum_withdrawal_amount_is': '最低可提金額為',
  'application_completed': '申請完成',
  'withdrawal_application_has_been_completed_you_can_check_the_current_application_status_in_the_withdrawal_log':
      '提款申請已完成，可於提款紀錄查詢目前申請進度。',
  'minimum_withdrawable_amount': '最低可提現金額',
  'flow_limit_details': '流水限額詳情',
  'accumulated_liquidity': '累積有效流水',
  'withdrawal_fee_will_be_charged_for_withdrawal_before_reaching_the_limit':
      '未達流水限額提現需支付提現手續費',
  'login_now': '立即登錄',
  'no_account_yet': '還沒有帳號',
  'forgot_your_password': '忘記密碼',
  'please_enter_your_password': '請輸入密碼',
  'password': '密碼',
  'username': '帳號',
  'letters_and_numbers': '6~12位字母及數字',
  'password_is_letters_and_numbers': '密碼為 8-20 位字母及數字',
  'account_is_digits_alphabetic_and_numeric': '帳號為 6~12 位字母及數字',
  'please_enter_your_username': '請輸入帳號',
  'incorrect_username_or_password': '帳號或密碼不正確',
  'login_error': '登入錯誤',
  'login_successful': '登入成功',
  'register_now': '立即註冊',
  'verify_password': '驗證密碼',
  'incorrect_secondary_password': '二次密碼不正確',
  'registration_error': '註冊錯誤',
  'registration_successful': '註冊成功',
  'download_app': '下載APP',
  'greetings_to_our_valued_users_global_gaming_invites_you_to_download_the_app_to_enhance_your_gaming_experience':
      '尊貴的用戶您好\n環球遊戲邀請您下載APP，提升遊戲體驗。',
  'this_password_is_only_for_the_first_time_you_log_in_to_the_app_please_be_sure_to_change_your_password_after_logging_in':
      '此組帳密僅提供首次登入APP使用\n請務必在登入後，更換帳號密碼。',
  'password_copied': '密碼已複製',
  'account_has_been_copied': '帳號已複製',
  'withdrawal': '提現',
  'balance': '餘額',
  'insufficient_password': '密碼長度不足',
  'wrong_password': '密碼錯誤',
  'duplicate_login': '帳號重複登入',
  'duplicated': '已複製',
  'currently_under_maintenance': '目前系統維護中',
  'estimated_maintenance_time': '預計維護時間 08:00-10:00',
  'please_try_again_later_sorry_for_the_inconvenience': '請稍後再試，造成不便請見諒',
  "game_maintenance_in_progress": "遊戲維護中",
  "the_game_is_under_maintenance_please_try_again_later": "遊戲維護中，請稍後再試",
  "login": "登入",
  "register": "註冊",
  "please_contact_customer_service_or_log_in_with_your_id_card":
      "請聯繫客服，或用身份卡登入",
  "all": "全部",
  "recent": "最近",
  "fish": "捕魚",
  "card": "棋牌",
  "slots": "電子",
  "live": "真人",
  "sports": "體育",
  "lottery": "彩票",
  "hot": "熱門",
  "alipay": "支付寶",
  "wechat": "微信",
  "bank": "網銀入款",
  "set_a_funds_pin": "設置資金密碼",
  "funds_pin": "資金密碼",
  "tips": "溫馨提醒",
};
