const Map<String, String> zhCnStrings = {
  'game_lobby': '游戏大厅',
  'register_login': '注册/登入',
  'close': '关闭',
  'open': '开启',
  'cancel': '取消',
  'confirm': '确认',
  'hot_events': '热门活动',
  'bank_transfer': '银行转帐',
  'trc_address': 'TRC-20地址',
  'account_information': '帐户资讯',
  'confirmation_of_transfer_and_delivery': '确认已转帐，送出！',
  'transfer_remarks': '转帐备注',
  'please_enter_the_last_digits_of_the_transfer_hash': '请输入转帐哈希值末 5 码',
  'please_enter_your_real_name': '请输入真实姓名',
  'account_name': '帐户姓名',
  'bank_card_number': '银行卡号',
  'branch_name': '支行名称',
  'bank_name': '银行名称',
  'estimated_amount': '预估上分金额',
  'exchange_rate': '汇率',
  'transfer_amount': '转帐金额',
  'there_are_no_available_payment_channels_please_try_again_later_or_contact_customer_service':
      '当前无可用支付渠道，请稍候再试或联系客服。',
  'deposit_amount': '存款金额',
  'get_the_link_to_reload': '取得充值连结...',
  'the_link_was_successful': '充值连结取得成功！',
  'failed_to_get_the_link_to_recharge_please_change_the_recharge_channel_or_contact_customer_service':
      '充值连结取得失败\n请更换充值渠道或联系客服',
  'open_top_up_page': '开启充值页',
  'wrong_name_format': '姓名格式错误',
  'wrong_verification_code': '验证码错误',
  'if_the_order_is_correct_please_enter_the_above_verification_code':
      '如订单无误，请输入以上验证码',
  'deposit': '存款',
  'deposit_history': '存款记录',
  'you_have_been_logged_out_please_log_in_again': '你已被登出，请重新登入',
  'warm_tips': '温馨提示',
  'please_be_sure_to_provide_true_information_to_facilitate_the_verification_of_the_transfer_data':
      '1. 请务必提供真实资讯，以利核对转帐资料。',
  'please_write_the_required_information_in_the_remittance_remarks_to_speed_up_the_recharge_process':
      '2. 请在汇款备注写入要求资讯，加速充值流程。',
  'no_payment_channel': '没有支付通道',
  'dollar': '',
  'send_offer': '送优惠',
  'payment_channel': '支付渠道',
  'order_confirmation': '订单确认',
  'transaction_failed': '交易失败',
  'there_are_many_people_paying_at_the_moment_please_try_again_later':
      '当前支付人数众多，请稍后再试！',
  'order_creation_failed_please_contact_our_customer_service': '订单建立失败，请联系客服',
  'payment_was_not_successful_please_try_to_pay_several_times':
      '1：支付不成功，请多次尝试支付。',
  'can_not_pull_up_the_payment_order_is_due_to_pull_up_the_order_more_people_please_try_to_pull_up_the_payment_several_times':
      '2：无法拉起支付订单，是由于拉起订单人数较多，请多次尝试拉起支付。',
  'please_contact_our_online_customer_service_if_the_recharge_is_successful_but_not_arrived':
      '3：充值成功未到账，请联系在线客服。',
  'please_select_deposit_amount': '请选择存款金额',
  'get_recharge_url': '取得充值网址',
  'we_are_trying_to_get_the_recharge_url_please_wait': '正在努力取得充值网址，请稍候...',
  'please_click_to_open_the_recharge_page': '已取得充值网址，点击开启充值页',
  'failed_to_get_the_website_address_please_choose_a_new_channel_or_contact_customer_service':
      '取得网址失败\n请重新选择渠道或联系客服',
  'please_select_payment_method': '请选择支付方式',
  'amount_to_be_paid': '需支付金额',
  'confirm_payment': '确认支付',
  'completed': '已完成',
  'failed': '失败',
  'no_record': '暂无纪录',
  'confirming': '确认中',
  'amount': '金额',
  'order_time': '订单时间',
  'order_number': '订单编号',
  'last_30_days': '近三十日',
  'last_7_days': '近七天',
  'yesterday': '昨天',
  'today': '今天',
  'application_time_enquiry': '申请时间查询',
  'status': '状态',
  'payment_confirmation': '支付确认',
  'bank_card_setting': '银行卡设置',
  'please_make_sure_you_fill_in_the_correct_information_to_avoid_affecting_the_payment':
      '绑定后不可更改，请确认资料填写正确，避免影响到帐。',
  'please_enter_your_bank_name': '请输入银行名称',
  'please_enter_the_correct_bank_name': '请输入正确的银行名称',
  'please_enter_the_name_of_the_branch_optional': '请输入支行名称(选填)',
  'card_number': '银行卡号',
  'please_enter_your_bank_card_number': '请输入您的银行卡号',
  'real_name': '真实姓名',
  'account_length': '帐户长度为16~19',
  'setup_successful': '设置成功',
  'password_length_should_be_digits': '密码长度应为6位数',
  'input_funds_pin': '输入资金密码',
  'please_enter_digits': '请输入6位数字',
  'the_password_should_be_the_same_for_the_second_time': '二次验证密码输入应相同',
  'confirm_password_again': '再次确认密码',
  'please_confirm_the_password_again': '请再次确认密码',
  'setting_failed': '设置失败',
  'successful': '设置成功',
  'return_to_the_lobby': '返回大厅',
  'customer_service': '客服',
  'recharge': '充值',
  'quit_the_game': '退出游戏',
  'do_you_really_want_to_quit_the_game': '你真的要退出游戏吗？',
  'failed_to_withdraw': '出款失败',
  'withdrawal_history': '提现纪录',
  'withdrawal_account': '提款帐户',
  'withdrawal_amount': '提款金额',
  'application_time': '申请时间',
  'update_time': '更新时间',
  'reviewing': '审核中',
  'bank_card': '银行卡',
  'type': '类型',
  'account': '帐户',
  'withdrawal_method': '提现方式',
  'please_complete_the_card_binding_before_withdrawing_money':
      '请完成银行卡绑定，方可进行提款',
  'go_to_binding': '前往绑定',
  'insufficient_liquidity_please_continue_to_play': '流水不足，请继续游戏',
  'if_you_have_not_reached_the_limit_need_to_pay_the_withdrawal_fee_of_estimated_click_to_confirm_to_send_out_the_withdrawal_order':
      '未达成流水限额\n需自行负担提现手续费 {fee} 元(预估)\n点击确认送出提现订单',
  'please_set_the_password_first': '请先设置资金密码',
  'go_to_settings': '前往设定',
  'game_withdrawal': '游戏提现',
  'limit': '流水限额',
  'achieved': '已达标',
  'not_reached': '未达标',
  'please_enter_the_withdrawal_amount': '请输入提现金额',
  'input_amount_must_not_be_less_than': '输入金额不得小于',
  'input_amount_must_not_be_greater_than_the_remaining_balance': '输入金额不得大于余额',
  'input_amount_is_in_wrong_format': '输入金额格式错误',
  'minimum_withdrawal_amount_is': '最低可提金额为',
  'application_completed': '申请完成',
  'withdrawal_application_has_been_completed_you_can_check_the_current_application_status_in_the_withdrawal_log':
      '提款申请已完成，可于提款纪录查询目前申请进度。',
  'minimum_withdrawable_amount': '最低可提现金额',
  'flow_limit_details': '流水限额详情',
  'accumulated_liquidity': '累积有效流水',
  'withdrawal_fee_will_be_charged_for_withdrawal_before_reaching_the_limit':
      '未达流水限额提现需支付提现手续费',
  'login_now': '立即登录',
  'no_account_yet': '还没有帐号',
  'forgot_your_password': '忘记密码',
  'please_enter_your_password': '请输入密码',
  'password': '密码',
  'username': '帐号',
  'letters_and_numbers': '6~12位字母及数字',
  'password_is_letters_and_numbers': '密码为 8-20 位字母及数字',
  'account_is_digits_alphabetic_and_numeric': '帐号为 6~12 位字母及数字',
  'please_enter_your_username': '请输入帐号',
  'incorrect_username_or_password': '帐号或密码不正确',
  'login_error': '登入错误',
  'login_successful': '登入成功',
  'register_now': '立即注册',
  'verify_password': '验证密码',
  'incorrect_secondary_password': '二次密码不正确',
  'registration_error': '注册错误',
  'registration_successful': '注册成功',
  'download_app': '下载APP',
  'greetings_to_our_valued_users_global_gaming_invites_you_to_download_the_app_to_enhance_your_gaming_experience':
      '尊贵的用户您好\n环球游戏邀请您下载APP，提升游戏体验。',
  'this_password_is_only_for_the_first_time_you_log_in_to_the_app_please_be_sure_to_change_your_password_after_logging_in':
      '此组帐密仅提供首次登入APP使用\n请务必在登入后，更换帐号密码。',
  'password_copied': '密码已复制',
  'account_has_been_copied': '帐号已复制',
  'withdrawal': '提现',
  'balance': '余额',
  'insufficient_password': '密码长度不足',
  'wrong_password': '密码错误',
  'duplicate_login': '帐号重复登入',
  'duplicated': '已复制',
  'currently_under_maintenance': '目前系统维护中',
  'estimated_maintenance_time': '预计维护时间 08:00-10:00',
  'please_try_again_later_sorry_for_the_inconvenience': '请稍后再试，造成不便请见谅',
  "game_maintenance_in_progress": "游戏维护中",
  "the_game_is_under_maintenance_please_try_again_later": "游戏维护中，请稍后再试",
  "login": "登入",
  "register": "注册",
  "please_contact_customer_service_or_log_in_with_your_id_card":
      "请联系客服，或用身份卡登入",
  "all": "全部",
  "recent": "最近",
  "fish": "捕鱼",
  "card": "棋牌",
  "slots": "电子",
  "live": "真人",
  "sports": "体育",
  "lottery": "彩票",
  "hot": "热门",
  "alipay": "支付宝",
  "wechat": "微信",
  "bank": "网银入款",
  "set_a_funds_pin": "设置资金密码",
  "funds_pin": "资金密码",
  "tips": "温馨提醒",
};
