const Map<String, String> liveEnUsStrings = {
  "a_certain_user": "A certain user",
  "auto_renewal": "Auto-renewal",
  "bid": "Bid",
  "cancel": "Cancel",
  "close": "Close",
  "command_list": "Command list",
  "comprehensive": "Comprehensive",
  "confirm": "Confirm",
  "copy_link": "Copy Link",
  "copy_successfully": "Copy Successfully",
  "daily_ranking": "Today",
  "data_updates_every_hour": "Data updates every hour",
  "day": "Days",
  "default_sorting": "Default Sorting",
  "diamond_leaderboard": "Contribution ranking",
  "ended": "Ended",
  "enter_paid_live": "Enter paid Live room",
  "error": "Error",
  "its_about_to_happen": "Loading",
  "fan_recommendations": "Fan Recommendations",
  "filter": "Filter",
  "follow": "Follow",
  "followed": "Followed",
  "followed_host": "Host",
  "followed_hosts": "Followed",
  "free": "Free",
  "free_live": "Free Live",
  "gift_list": "Gift List",
  "its_worth_wating_for_the_good_stuff": "Loading",
  "host_ranking": "Host Ranking",
  "hot_recommendations": "Hot Recommendations",
  "insufficient_diamonds_please_recharge":
      "Insufficient diamonds, please recharge",
  "its_not_ready_yet": "Loading",
  "joined": "Joined",
  "language": "Language",
  "leaderboard": "Ranking",
  "let_the_file_load_for_a_while": "Loading",
  "live_broadcast_has_ended": "Live broadcast has ended",
  "live_broadcasting": "On live",
  "live_preview": "Preview",
  "live_room_is_not_open": "Live room is not open",
  "we_are_trying_to_load_t": "Loading",
  "minute": "Minute",
  "point": "Point",
  "monthly_ranking": "This month",
  "most_followed": "Most Followed",
  "most_viewed": "Most Viewed",
  "new_hosts": "New Hosts",
  "newcomer": "New Hosts",
  "no_more": "No more",
  "no_such_chat_room": "No such chat room",
  "not_enough_diamonds": "Not enough diamonds",
  "number_of_followers": "Number of Followers",
  "paid": "Paid",
  "paid_live": "Paid Live",
  "popularity": "Popularity",
  "recent_searches": "Search History",
  "say_something_to_the_host": "Chat with host...",
  "search": "Search",
  "search_host_id_or_nickname": "Search Host ID or Nickname",
  "send": "Send",
  "send_command": "Send Command",
  "send_gift": "Send Gift",
  "send_successfully": "Send Successfully",
  "share_to": "Share to",
  "sort": "Sort",
  "sorting_condition": "Sorting condition",
  "its_a_big_file": "Loading",
  "there_is_nothing_here": "You've scrolled all the way down",
  "this_live_session": "Live",
  "timed_payment": "Timed payment",
  "today": "Today",
  "type_of_live_broadcast": "Live room type",
  "type_of_payment": "Payment type",
  "unlimited": "All",
  "weekly_ranking": "This week",
  "whether_to_continue_after_paid_time_expires":
      "Whether to continue after paid time expires",
  "trying_to_move_bricks": "Loading",
  "fans": "fans",
  "preview": "Preview",
  "recommend": "Recommend",
  "account_or_password_error": "Account or password error",
  "please_login_first": "Please log in first",
  "conflict": "You are already using this account on another device"
};
