const Map<String, String> liveEnUsStrings = {
  "a_certain_user": "A certain user",
  "auto_renewal": "Auto-renewal",
  "bid": "Bid",
  "cancel": "Cancel",
  "command_list": "Command list",
  "comprehensive": "Comprehensive",
  "confirm": "Confirm",
  "copy_link": "Copy Link",
  "copy_successfully": "Copy Successfully",
  "daily_ranking": "Daily Ranking",
  "data_updates_every_hour": "Data updates every hour",
  "day": "Day",
  "default_sorting": "Default Sorting",
  "diamond_leaderboard": "Diamond Leaderboard",
  "ended": "Ended",
  "enter_paid_live": "Enter Paid Live",
  "error": "Error",
  "exciting_moments_are_coming_soon": "Exciting moments are coming soon",
  "fan_recommendations": "Fan Recommendations",
  "filter": "Filter",
  "follow": "Follow",
  "followed": "Followed",
  "followed_host": "Followed Host",
  "followed_hosts": "Followed Hosts",
  "free": "Free",
  "free_live": "Free Live",
  "gift_list": "Gift List",
  "good_things_are_worth_the_wait": "Good things are worth the wait",
  "host_ranking": "Host Ranking",
  "hot_recommendations": "Hot Recommendations",
  "insufficient_diamonds_please_recharge":
      "Insufficient diamonds, please recharge",
  "its_not_ready_yet_please_take_your_time":
      "It's not ready yet, please take your time",
  "joined": "Joined",
  "leaderboard": "Leaderboard",
  "let_the_file_load_for_a_while": "Let the file load for a while",
  "live_broadcast_has_ended": "Live broadcast has ended",
  "live_broadcasting": "Live Broadcasting",
  "live_preview": "Live Preview",
  "live_room_is_not_open": "Live room is not open",
  "loading": "Loading",
  "minute": "Minute",
  "point": "Point",
  "monthly_ranking": "Monthly Ranking",
  "most_followed": "Most Followed",
  "most_viewed": "Most Viewed",
  "new_hosts": "New Hosts",
  "newcomer": "Newcomer",
  "no_more": "No more",
  "no_such_chat_room": "No such chat room",
  "not_enough_diamonds": "Not enough diamonds",
  "number_of_followers": "Number of Followers",
  "paid": "Paid",
  "paid_live": "Paid Live",
  "popularity": "Popularity",
  "recent_searches": "Recent Searches",
  "say_something_to_the_host": "Say something to the host...",
  "search": "Search",
  "search_host_id_or_nickname": "Search Host ID or Nickname",
  "send": "Send",
  "send_command": "Send Command",
  "send_gift": "Send Gift",
  "send_successfully": "Send Successfully",
  "share_to": "Share to",
  "sort": "Sort",
  "sorting_condition": "Sorting condition",
  "the_file_is_large_please_wait": "The file is large, please wait",
  "there_is_nothing_here": "There is nothing here",
  "this_live_session": "This live session",
  "timed_payment": "Timed payment",
  "today": "Today",
  "type_of_live_broadcast": "Type of live broadcast",
  "type_of_payment": "Type of payment",
  "unlimited": "Unlimited",
  "weekly_ranking": "Weekly Ranking",
  "whether_to_continue_after_paid_time_expires":
      "Whether to continue after paid time expires",
  "working_hard": "Working hard",
  "fans": "fans",
  "preview": "Preview",
};
