const Map<String, String> liveIdIdStrings = {
  "a_certain_user": "Seorang pengguna tertentu",
  "auto_renewal": "Pembaharuan otomatis",
  "bid": "Tawar",
  "cancel": "Batal",
  "close": "menutup",
  "command_list": "Daftar perintah",
  "comprehensive": "Komprehensif",
  "confirm": "Konfirmasi",
  "copy_link": "Salin Tautan",
  "copy_successfully": "Salin Berhasil",
  "daily_ranking": "Peringkat Harian",
  "data_updates_every_hour": "Data diperbarui setiap jam",
  "day": "Hari",
  "default_sorting": "Pengurutan Default",
  "diamond_leaderboard": "Papan Peringkat Berlian",
  "ended": "Berakhir",
  "enter_paid_live": "Masuk Langsung Berbayar",
  "error": "Kesalahan",
  "its_about_to_happen": "Sedang memuat",
  "fan_recommendations": "Rekomendasi Penggemar",
  "filter": "Filter",
  "follow": "Ikuti",
  "followed": "Diikuti",
  "followed_host": "Pemimpin siaran langsung yang diikuti",
  "followed_hosts": "Pemimpin siaran langsung yang Diikuti",
  "free": "Gratis",
  "free_live": "Siaran langsung Gratis",
  "gift_list": "Daftar Hadiah",
  "its_worth_wating_for_the_good_stuff": "Sedang memuat",
  "host_ranking": "Peringkat Pemimpin siaran langsung",
  "hot_recommendations": "Rekomendasi Hot",
  "insufficient_diamonds_please_recharge":
      "Berlian tidak mencukupi, silakan isi ulang",
  "its_not_ready_yet": "Sedang memuat",
  "joined": "Bergabung",
  "language": "Bahasa",
  "leaderboard": "Papan Peringkat",
  "let_the_file_load_for_a_while": "Sedang memuat",
  "live_broadcast_has_ended": "Siaran langsung telah berakhir",
  "live_broadcasting": "Siaran Langsung",
  "live_preview": "Pratinjau Langsung",
  "live_room_is_not_open": "Kamar langsung belum dibuka",
  "we_are_trying_to_load_t": "Sedang memuat",
  "minute": "Menit",
  "point": "Poin",
  "monthly_ranking": "Peringkat Bulanan",
  "most_followed": "Paling Banyak Diikuti",
  "most_viewed": "Paling Banyak Dilihat",
  "new_hosts": "Pemimpin siaran langsung Baru",
  "newcomer": "Pendatang Baru",
  "no_more": "Tidak ada lagi",
  "no_such_chat_room": "Tidak ada ruang obrolan seperti itu",
  "not_enough_diamonds": "Tidak cukup berlian",
  "number_of_followers": "Jumlah Pengikut",
  "paid": "Berbayar",
  "paid_live": "Siaran langsung Berbayar",
  "popularity": "Popularitas",
  "recent_searches": "Pencarian Terbaru",
  "say_something_to_the_host":
      "Katakan sesuatu kepada Pemimpin siaran langsung...",
  "search": "Cari",
  "search_host_id_or_nickname":
      "Cari ID Pemimpin siaran langsung atau Nama Panggilan",
  "send": "Kirim",
  "send_command": "Kirim Perintah",
  "send_gift": "Kirim Hadiah",
  "send_successfully": "Kirim Berhasil",
  "share_to": "Bagikan ke",
  "sort": "Urutkan",
  "sorting_condition": "Kondisi Pengurutan",
  "its_a_big_file": "Sedang memuat",
  "there_is_nothing_here": "Tidak ada yang di sini",
  "this_live_session": "Sesi siaran langsung ini",
  "timed_payment": "Pembayaran berjadwal",
  "today": "Hari ini",
  "type_of_live_broadcast": "Jenis siaran langsung",
  "type_of_payment": "Jenis pembayaran",
  "unlimited": "Tanpa batas",
  "weekly_ranking": "Peringkat Mingguan",
  "whether_to_continue_after_paid_time_expires":
      "Apakah akan melanjutkan setelah waktu berbayar berakhir",
  "trying_to_move_bricks": "Sedang memuat",
  "fans": "penggemar",
  "preview": "Pratinjau",
  "recommend": "Merekomendasikan",
};
