const Map<String, String> liveViVnStrings = {
  "a_certain_user": "Một người dẫn chương trình cụ thể",
  "auto_renewal": "Tự động gia hạn",
  "bid": "Chào giá",
  "cancel": "Hủy",
  "command_list": "Danh sách lệnh",
  "comprehensive": "Toàn diện",
  "confirm": "Xác nhận",
  "copy_link": "Sao chép liên kết",
  "copy_successfully": "Sao chép thành công",
  "daily_ranking": "Xếp hạng hàng ngày",
  "data_updates_every_hour": "Cập nhật dữ liệu mỗi giờ",
  "day": "Ngày",
  "default_sorting": "Sắp xếp mặc định",
  "diamond_leaderboard": "Bảng xếp hạng Kim cương",
  "ended": "Kết thúc",
  "enter_paid_live": "Nhập trả phí trực tiếp",
  "error": "Lỗi",
  "exciting_moments_are_coming_soon": "Những khoảnh khắc thú vị sắp đến",
  "fan_recommendations": "Đề xuất của Fan",
  "filter": "Bộ lọc",
  "follow": "Theo dõi",
  "followed": "Đã theo dõi",
  "followed_host": "Người dẫn chương trình đã theo dõi",
  "followed_hosts": "Các người dẫn chương trình đã theo dõi",
  "free": "Miễn phí",
  "free_live": "Trực tiếp miễn phí",
  "gift_list": "Danh sách quà tặng",
  "good_things_are_worth_the_wait": "Những điều tốt lành đáng chờ đợi",
  "host_ranking": "Xếp hạng người dẫn chương trình",
  "hot_recommendations": "Đề xuất nóng",
  "insufficient_diamonds_please_recharge":
      "Không đủ kim cương, vui lòng nạp tiền",
  "its_not_ready_yet_please_take_your_time":
      "Chưa sẵn sàng, vui lòng dành thời gian của bạn",
  "joined": "Tham gia",
  "leaderboard": "Bảng xếp hạng",
  "let_the_file_load_for_a_while": "Để tệp tải trong một thời gian",
  "live_broadcast_has_ended": "Phát sóng trực tiếp đã kết thúc",
  "live_broadcasting": "Phát sóng trực tiếp",
  "live_preview": "Xem trước trực tiếp",
  "live_room_is_not_open": "Phòng trực tiếp không mở",
  "loading": "Đang tải",
  "minute": "Phút",
  "point": "Điểm",
  "monthly_ranking": "Xếp hạng hàng tháng",
  "most_followed": "Được theo dõi nhiều nhất",
  "most_viewed": "Được xem nhiều nhất",
  "new_hosts": "Người dẫn chương trình mới",
  "newcomer": "Người mới",
  "no_more": "Không còn nữa",
  "no_such_chat_room": "Không có phòng trò chuyện như vậy",
  "not_enough_diamonds": "Không đủ kim cương",
  "number_of_followers": "Số lượng người theo dõi",
  "paid": "Trả phí",
  "paid_live": "Trực tiếp trả phí",
  "popularity": "Độ phổ biến",
  "recent_searches": "Tìm kiếm gần đây",
  "say_something_to_the_host": "Nói gì đó với người dẫn chương trình...",
  "search": "Tìm kiếm",
  "search_host_id_or_nickname":
      "Tìm kiếm ID hoặc biệt danh người dẫn chương trình",
  "send": "Gửi",
  "send_command": "Gửi lệnh",
  "send_gift": "Gửi quà tặng",
  "send_successfully": "Gửi thành công",
  "share_to": "Chia sẻ đến",
  "sort": "Sắp xếp",
  "sorting_condition": "Điều kiện sắp xếp",
  "the_file_is_large_please_wait": "Tệp lớn, vui lòng đợi",
  "there_is_nothing_here": "Không có gì ở đây",
  "this_live_session": "Phiên trực tiếp này",
  "timed_payment": "Thanh toán theo thời gian",
  "today": "Hôm nay",
  "type_of_live_broadcast": "Loại phát sóng trực tiếp",
  "type_of_payment": "Loại thanh toán",
  "unlimited": "Không giới hạn",
  "weekly_ranking": "Xếp hạng hàng tuần",
  "whether_to_continue_after_paid_time_expires":
      "Có tiếp tục sau khi thời gian trả phí kết thúc không",
  "working_hard": "Đang làm việc chăm chỉ",
  "fans": "cái quạt",
  "preview": "Xem trước",
  "recommend": "khuyến nghị",
};
