const Map<String, String> sharedEnUsStrings = {
  "fullscreen_view": "Fullscreen view",
  "please_enter_your_account": "Please enter your account",
  "please_enter_your_password": "Please enter your password",
  "login_error": "Login error",
  "incorrect_account_or_password": "Incorrect account or password",
  "account_must_be_6-12_alphanumeric_characters":
      "Account must be 6-12 alphanumeric characters",
  "password_must_be_8-20_alphanumeric_characters":
      "Password must be 8-20 alphanumeric characters",
  "please_enter_verification_password": "Please enter verification password",
  "verification_password_does_not_match":
      "Verification password does not match",
  "registration_error": "Registration error",
  "account_already_exists": "Account already exists",
  "million": "Million",
  "duplicate_account_login": "Duplicate account login",
  "confirm": "Confirm",
  "content_updated": "Content updated",
  "play": "Play",
  "download": "Download",
  "latest": "Latest",
  "hottest": "Hottest",
  "all_regions": "All regions",
  "all_companies": "All companies",
  "all_content_creators": "All content creators",
  "all_payment_types": "All payment types",
  "free": "Free",
  "coins": "Coins",
  "fetching_latest_resources": "Loading...",
  "version": "Version",
  "checking_connection": "Connection...",
  "system_maintenance": "System maintenance, please try again later.",
  "check_for_updates": "Checking for updates...",
  "new_version_available": "New version available",
  "new_version_released_please_update":
      "New version released, please update for smoother viewing experience.",
  "update_version": "Update version",
  "experience_now": "Experience now",
  "not_upgrading_now": "Not upgrading now",
  "user_login": "login...",
  "account_creation_failed_device_disabled":
      "Account creation failed, device disabled.",
  "account_creation_failed": "Account creation failed.",
  "failure": "Failed",
  "actors": "Actors",
  "publishers": "Publishers",
  "redemption_successful": "Redemption successful",
  "tags": "Tags",
  "games": "Games",
  "no_more_video": "no more videos",
  "back": "back",
  "account_already_exists_pls_reenter":
      "Account already exists, please re-enter the account.",
  "you_have_been_logged_out_please_log_in_again":
      "You have been logged out, please log in again.",
  "purchase_failed": "Purchase failed",
  "insufficient_gold_balance": "Insufficient balance",
  "go_to_top_up_now_for_full_exp": "Top up to enjoy the full experience",
  "go_to_top_up": "Top up now",
  "cancel": "Cancel",
  "count_gold_coins_to_unlock": "Coins to unlock",
  "upgrade_to_full_version": "Upgrade to full version",
  "try_watching_ends": "Upgrade to full version",
  "unlock_for_full_playback": "Upgrade to full version",
  "duration": "Length:",
  "become_vip": "Become VIP",
  "this_movie_is_available_for_purchase":
      "This movie is available for purchase.",
  "price": "Price:",
  "your_current_coins": "Your coins:",
  "pay_to_watch": "Payment",
  "end_of_trial_upgrade_to_full_version": "Upgrade to Full Version",
  "length_of_film": "Length:",
  "unlocked_for_full_playback": "Unlocked Now",
  "upgrade_now_for_unlock": "Upgrade Now",
};
