const Map<String, String> sharedIdIdStrings = {
  "fullscreen_view": "Tampilan Layar Penuh",
  "please_enter_your_account": "Silakan masukkan akun Anda",
  "please_enter_your_password": "Silakan masukkan kata sandi Anda",
  "login_error": "Masalah masuk",
  "incorrect_account_or_password": "Akun atau kata sandi salah",
  "account_must_be_6-12_alphanumeric_characters":
      "Akun harus terdiri dari 6-12 karakter alfanumerik",
  "password_must_be_8-20_alphanumeric_characters":
      "Kata sandi harus terdiri dari 8-20 karakter alfanumerik",
  "please_enter_verification_password":
      "Silakan masukkan kata sandi verifikasi",
  "verification_password_does_not_match": "Kata sandi verifikasi tidak cocok",
  "registration_error": "Kesalahan registrasi",
  "account_already_exists": "Akun sudah ada",
  "million": "Juta",
  "duplicate_account_login": "Login akun yang sama ganda",
  "confirm": "Konfirmasi",
  "content_updated": "Konten diperbarui",
  "play": "Putar",
  "download": "Unduh",
  "latest": "Terbaru",
  "hottest": "Paling populer",
  "all_regions": "Semua wilayah",
  "all_companies": "Semua perusahaan",
  "all_content_creators": "Semua pembuat konten",
  "all_payment_types": "Semua jenis pembayaran",
  "free": "Gratis",
  "coins": "Koin",
  "fetching_latest_resources": "Memuat...",
  "version": "Versi",
  "checking_connection": "Koneksi...",
  "system_maintenance": "Pemeliharaan sistem, silakan coba lagi nanti.",
  "check_for_updates": "Memeriksa pembaruan...",
  "new_version_available": "Versi baru tersedia",
  "new_version_released_please_update":
      "Versi baru telah dirilis, harap perbarui untuk pengalaman menonton yang lebih lancar.",
  "update_version": "Perbarui versi",
  "experience_now": "Pengalaman sekarang",
  "not_upgrading_now": "Tidak ditingkatkan saat ini",
  "user_login": "masuk",
  "account_creation_failed_device_disabled":
      "Pembuatan akun gagal, perangkat dinonaktifkan.",
  "account_creation_failed": "Pembuatan akun gagal.",
  "failure": "Gagal",
  "actors": "Pemain",
  "publishers": "Penerbit",
  "redemption_successful": "Penebusan berhasil",
  "tags": "Tag",
  "games": "Permainan",
  "no_more_video": "Tidak ada lagi video",
  "back": "Kembali",
  "account_already_exists_pls_reenter":
      "Akun sudah ada, silakan masukkan akun lagi.",
  "you_have_been_logged_out_please_log_in_again":
      "Anda telah keluar, silakan masuk kembali.",
  "purchase_failed": "Pembelian gagal",
  "insufficient_gold_balance": "Saldo tidak mencukupi",
  "go_to_top_up_now_for_full_exp": "Isi ulang untuk menikmati pengalaman penuh",
  "go_to_top_up": "Muat sekarang",
  "cancel": "Batal",
  "count_gold_coins_to_unlock": "Koin untuk membuka kunci",
  "upgrade_to_full_version": "Tingkatkan ke versi lengkap",
  "try_watching_ends": "Tingkatkan ke versi lengkap",
  "unlock_for_full_playback": "Tingkatkan ke versi lengkap",
  "duration": "Durasi film:",
  "become_vip": "Menjadi VIP",
  "this_movie_is_available_for_purchase":
      "Video ini memerlukan pembelian untuk diakses",
  "price": "Harga:",
  "your_current_coins": "Koin Anda:",
  "pay_to_watch": "Pembayaran",
  "end_of_trial_upgrade_to_full_version": "Tingkatkan ke Versi Penuh",
  "length_of_film": "Durasi film:",
  "unlocked_for_full_playback": "Sudah Dibuka Sekarang",
  "upgrade_now_for_unlock": "Tingkatkan Sekarang",
  "unmute": "Bunyikan",
  "serialization": "Series",
  "serializing_to_number": "Saat ini diserialkan hingga",
  "episode": "ep",
  "number": "No.",
  "other_recommended_posts": "Direkomendasikan",
  "view_more": "Lihat lebih banyak",
  "become_a _vip_to_unlock": "Menjadi VIP",
  "gold_coins_unlock": "Koin buka",
  "coming_soon": "Keseruan segera hadir",
  "activate_vip_for_free": "Aktifkan VIP secara gratis",
  "view_details": "Lihat detail",
  "want_to_watch": "Ingin menonton，",
  "unlock_now": "Buka sekarang",
  "say_something": "Katakan sesuatu...",
  "please_login": "Harap masuk",
  "login": "Masuk",
  "send": "Kirim",
  "nothing_here": "Tidak ada apa pun di sini",
  "nothing_more": "tidak ada lagi",
};
