const Map<String, String> sharedJaJpStrings = {
  "fullscreen_view": "フルスクリーンで表示",
  "please_enter_your_account": "アカウントを入力してください",
  "please_enter_your_password": "パスワードを入力してください",
  "login_error": "ログインエラー",
  "incorrect_account_or_password": "アカウントまたはパスワードが正しくありません",
  "account_must_be_6-12_alphanumeric_characters": "アカウントは6〜12桁の英数字である必要があります",
  "password_must_be_8-20_alphanumeric_characters": "パスワードは8〜20桁の英数字である必要があります",
  "please_enter_verification_password": "確認用パスワードを入力してください",
  "verification_password_does_not_match": "確認用パスワードが一致しません",
  "registration_error": "登録エラー",
  "account_already_exists": "アカウントは既に存在します",
  "million": "百万",
  "duplicate_account_login": "重複したアカウントのログイン",
  "you_have_been_logged_out_please_log_in_again": "ログアウトされました。もう一度ログインしてください",
  "confirm": "確認",
  "content_updated": "コンテンツが更新されました",
  "play": "再生",
  "download": "ダウンロード",
  "latest": "最新",
  "hottest": "最も人気のある",
  "all_regions": "すべての地域",
  "all_companies": "すべての企業",
  "all_content_creators": "すべてのコンテンツクリエイター",
  "all_payment_types": "すべての支払い方法",
  "free": "無料",
  "coins": "コイン",
  "fetching_latest_resources": "最新のリソースを取得しています...",
  "version": "バージョン",
  "checking_connection": "接続を確認しています...",
  "system_maintenance": "システムメンテナンス中です。後でもう一度お試しください。",
  "check_for_updates": "更新を確認しています...",
  "new_version_available": "新しいバージョンが利用可能です",
  "new_version_released_please_update":
      "新しいバージョンがリリースされました。よりスムーズな視聴体験のために更新してください。",
  "update_version": "バージョンを更新",
  "experience_now": "今すぐ体験",
  "not_upgrading_now": "現在はアップグレードしていません",
  "login": "ログインエラー",
  "account_creation_failed_device_disabled": "アカウント作成に失敗しました。デバイスが無効になっています。",
  "account_creation_failed": "アカウント作成に失敗しました。",
  "failed": "失敗",
  "actors": "俳優",
  "publishers": "出版者",
  "redemption_successful": "交換が成功しました",
  "tags": "タグ",
  "games": "ゲーム",
  "loading": "読み込み中...",
  "system_under_maintenance_please_try_again_later":
      "システムメンテナンス中です。後でもう一度お試しください。",
  "a_new_version_has_been_released_for_a_smoother_experience_please_update":
      "新しいバージョンがリリースされました。よりスムーズな体験のため、アップデートしてください。",
  "update_now": "今すぐ更新",
  "do_not_upgrade": "アップグレードしない",
  "user_login": "ユーザーログイン...",
  "failure": "失敗",
  "getting_latest_resources": "最新のリソースを取得中...",
};
