const Map<String, String> sharedViVnStrings = {
  "fullscreen_view": "Chế độ xem toàn màn hình",
  "please_enter_your_account": "Vui lòng nhập tài khoản của bạn",
  "please_enter_your_password": "Vui lòng nhập mật khẩu của bạn",
  "login_error": "Lỗi đăng nhập",
  "incorrect_account_or_password": "Tài khoản hoặc mật khẩu không chính xác",
  "account_must_be_6-12_alphanumeric_characters":
      "Tài khoản phải có 6-12 ký tự chữ và số",
  "password_must_be_8-20_alphanumeric_characters":
      "Mật khẩu phải có 8-20 ký tự chữ và số",
  "please_enter_verification_password": "Vui lòng nhập mật khẩu xác nhận",
  "verification_password_does_not_match": "Mật khẩu xác nhận không khớp",
  "registration_error": "Lỗi đăng ký",
  "account_already_exists": "Tài khoản đã tồn tại",
  "million": "Triệu",
  "duplicate_account_login": "Tài khoản đã đăng nhập trùng lặp",
  "confirm": "Xác nhận",
  "content_updated": "Nội dung đã được cập nhật",
  "play": "Phát",
  "download": "Tải xuống ngay",
  "latest": "Mới nhất",
  "hottest": "Nổi bật nhất",
  "all_regions": "Tất cả các khu vực",
  "all_companies": "Tất cả các công ty",
  "all_content_creators": "Tất cả các nhà tài trợ",
  "all_payment_types": "Tất cả các loại thanh toán",
  "free": "Miễn phí",
  "coins": "Đồng xu",
  "fetching_latest_resources": "Đang tải...",
  "version": "Phiên bản",
  "checking_connection": "Kết nối...",
  "system_maintenance": "Hệ thống đang bảo trì, vui lòng thử lại sau.",
  "check_for_updates": "Kiểm tra cập nhật...",
  "new_version_available": "Đã có phiên bản mới",
  "new_version_released_please_update":
      "Đã phát hành phiên bản mới, vui lòng cập nhật để có trải nghiệm xem phim mượt mà hơn.",
  "update_version": "Cập nhật phiên bản",
  "experience_now": "Trải nghiệm ngay",
  "not_upgrading_now": "Tạm thời không nâng cấp",
  "user_login": "đăng nhập",
  "account_creation_failed_device_disabled":
      "Tạo tài khoản không thành công, thiết bị đã bị vô hiệu hóa.",
  "account_creation_failed": "Tạo tài khoản không thành công.",
  "failure": "Thất bại",
  "actors": "Diễn viên",
  "publishers": "Nhà xuất bản",
  "redemption_successful": "Quy đổi thành công",
  "tags": "Thẻ",
  "games": "Trò chơi",
  "no_more_video": "Không còn video nào nữa",
  "back": "Quay lại",
  "account_already_exists_pls_reenter":
      "Tài khoản đã tồn tại, vui lòng nhập lại tài khoản.",
  "you_have_been_logged_out_please_log_in_again":
      "Bạn đã bị đăng xuất, vui lòng đăng nhập lại.",
  "purchase_failed": "Mua hàng không thành công",
  "insufficient_gold_balance": "Số dư không đủ",
  "go_to_top_up_now_for_full_exp": "Nạp tiền để tận hưởng trải nghiệm đầy đủ",
  "go_to_top_up": "Nạp ngay",
  "cancel": "Hủy",
  "count_gold_coins_to_unlock": "Sử dụng xu để mở khóa",
  "upgrade_to_full_version": "Mở khóa để phát lại đầy đủ",
  "try_watching_ends": "Mở khóa để phát lại đầy đủ",
  "unlock_for_full_playback": "Mở khóa để phát lại đầy đủ",
  "duration": "Thời lượng phim:",
  "become_vip": "Trở thành VIP",
  "this_movie_is_available_for_purchase":
      "Sau khi xem xong, bạn cần phải mua để xem tiếp video này",
  "price": "Giá cả:",
  "your_current_coins": "Đồng xu của bạn:",
  "pay_to_watch": "Thanh toán",
  "end_of_trial_upgrade_to_full_version": "Nâng cấp lên phiên bản đầy đủ",
  "length_of_film": "Thời lượng phim:",
  "unlocked_for_full_playback": "Đã mở khóa ngay",
  "upgrade_now_for_unlock": "Nâng cấp ngay",
  "unmute": "Bật tiếng",
  "serialization": "Seri",
  "serializing_to_number": "Hiện đang phát hành đến",
  "episode": "ep",
  "number": "Số",
  "other_recommended_posts": "Đề xuất",
  "view_more": "Xem thêm",
  "become_a_vip_to_unlock": "VIP để mở khóa",
  "gold_coins_unlock": "Mở khóa bằng xu",
  "coming_soon": "Sắp tới sẽ có những điều thú vị",
  "activate_vip_for_free": "Kích hoạt VIP miễn phí",
  "view_details": "Xem chi tiết",
  "want_to_watch": "Muốn xem",
  "unlock_now": "Mở khóa ngay",
  "say_something": "Nói gì đó...",
  "please_login": "Vui lòng đăng nhập",
  "login": "Đăng nhập",
  "send": "Gửi",
  "nothing_here": "Ở đây không có gì",
  "nothing_more": "không còn nữa",
  "comment": "Bình luận",
  "collapse": "Thu gọn",
  "expand": "Mở rộng",
  "i_want_to_report": "Báo cáo",
  "delete_comment": "Xóa bỏ",
  "please_select_a_reason": "Chọn Lý do",
  "please_select_type": "Chọn Loại",
};
