const Map<String, String> sharedZhCnStrings = {
  "fullscreen_view": "全屏观看",
  "please_enter_your_account": "请输入帐号",
  "please_enter_your_password": "请输入密码",
  "login_error": "登录错误",
  "incorrect_account_or_password": "账号或密码不正确",
  "account_must_be_6-12_alphanumeric_characters": "账号为6-12位字母及数字",
  "password_must_be_8-20_alphanumeric_characters": "密码为8-20位字母及数字",
  "please_enter_verification_password": "请输入验证密码",
  "verification_password_does_not_match": "验证密码不一致",
  "registration_error": "注册错误",
  "account_already_exists": "账号已存在",
  "million": "万",
  "duplicate_account_login": "账号重复登录",
  "you_have_been_logged_out_please_log_in_again": "你已被登出，请重新登录",
  "confirm": "确认",
  "content_updated": "内容已更新",
  "play": "播放",
  "download": "立即下载",
  "latest": "最新",
  "hottest": "最热",
  "all_regions": "全部地区",
  "all_companies": "全部厂商",
  "all_content_creators": "全部UP主",
  "all_payment_types": "全部付费类型",
  "free": "免费",
  "coins": "金币",
  "fetching_latest_resources": "获取最新资源...",
  "version": "版本",
  "checking_connection": "线路检查中...",
  "system_maintenance": "系统维护中，请稍后再试。",
  "check_for_updates": "检查更新...",
  "loading": "加载中...",
  "system_under_maintenance_please_try_again_later": "系统维护中，请稍后再试。",
  "new_version_available": "已有新版本",
  "a_new_version_has_been_released_for_a_smoother_experience_please_update":
      "已发布新版本，为了更流畅的体验，请更新版本。",
  "update_now": "更新版本",
  "experience_now": "立即体验",
  "do_not_upgrade": "暂不升级",
  "user_login": "用户登录...",
  "account_creation_failed_device_disabled": "账号创建失败，设备被禁用。",
  "failure": "失败",
  "account_creation_failed": "账号创建失败。",
  "getting_latest_resources": "获取最新资源...",
};
