enum ColorKeys {
  primary,
  accent,
  background,
  textPrimary,
  textSecondary,
  buttonBgPrimary,
  buttonBgSecondary,
  buttonBgGradientPrimary,
  buttonBgGradientSecondary,
  buttonBgCancel,
  buttonBgDisable,
  noImageBgTop,
  noImageBgBottom,
  menuColor,
  menuActiveColor,
  dividerColor,
}
